{% set name = "mlx-image" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlx_image-{{ version }}.tar.gz
  sha256: fd64a9017801a6ae620c05f4f867987bb6b59a80ff88d0844af4d6b2cad8df22

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - mlx 0.21.0
    - numpy 1.26.2
    - tqdm
    - safetensors 0.4.2
    - opencv-python 4.9.0.80
    - pillow 10.2.0
    - pandas 2.2.1
    - matplotlib-base
    - albumentations 1.4.1
    - types-pyyaml >=6.0.12.12,<7
    - huggingface_hub 0.21.4

test:
  imports:
    - mlxim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Apple MLX image models library
  home: https://github.com/riccardomusmeci/mlx-image
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
