{% set python_min = "3.10.0" %}
{% set name = "mlx-image" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlx_image-{{ version }}.tar.gz
  sha256: 31526380f93892b594bd2120680211ee5ccac8df6614d5999e8ca716afe17c26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - mlx
    - numpy 1.26.2
    - tqdm
    - safetensors
    - opencv
    - pillow
    - pandas
    - matplotlib-base
    - albumentations
    - types-pyyaml >=6.0.12,<7.0.0
    - huggingface_hub

test:
  imports:
    - mlxim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Apple MLX image models library
  home: https://github.com/riccardomusmeci/mlx-image
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
