schema_version: 1

context:
  name: mlx-image
  version: 0.1.9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mlx_image-${{ version }}.tar.gz
  sha256: 31526380f93892b594bd2120680211ee5ccac8df6614d5999e8ca716afe17c26

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - mlx 0.24.2.*
    - numpy 1.26.2.*
    - tqdm
    - safetensors 0.4.2.*
    - opencv 4.9.0.80.*
    - pillow 10.4.0.*
    - pandas 2.2.1.*
    - matplotlib-base
    - albumentations 1.4.1.*
    - types-pyyaml >=6.0.12,<7.0.0
    - huggingface_hub 0.24.0.*
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - mlxim
      pip_check: true

about:
  summary: Apple MLX image models library
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/riccardomusmeci/mlx-image

extra:
  recipe-maintainers:
    - xhochy
